/*
* �ㅽ겕濡ㅻ컮�� �붿옄�몄쓣 �낇엳湲� �꾪븳 ��泥� �ㅽ겕由쏀듃
* Alternate script for scrollbar design
* Info - http://www.psyonline.kr/1330044766
* Demo - http://www.psyonline.kr/plugin/fakescroll/demo.html
*/
var fakescroll=function(){var g={defaultoption:{scrollsize:100,scrollsizefix:0,scrollsizelock:!1,tracksize:0,outsidetrack:null,barsize:"auto",barminsize:20,trackhtml:"",barhtml:"",animate:!0,hide:!1,nointeract:!1,useswipe:!0,directionlock:!0,disable:!1,blockparentscroll:!1,tag:"div",usetransform:"translate3d"},cssclass:{content:"scroll-content",neutralzone:"scroll-neutralzone",x:["scroll-track scroll-track-x","scroll-bar scroll-bar-x","scroll-arrow scroll-arrow-left","scroll-arrow scroll-arrow-right",
"scroll-content-x"],y:["scroll-track scroll-track-y","scroll-bar scroll-bar-y","scroll-arrow scroll-arrow-up","scroll-arrow scroll-arrow-down","scroll-content-y"],iosmode:"ios"},items:[],set:function(a,c,b){var e,h,f,d,l,k,m=g.defaultoption,n=g.cssclass,r=g.items,t=g.handle,p=g.createtag,q=g.scrollbar,s=g.style,w=g.findelement,u=g.remove;l=g.browser;var v=!1;a=w(a);if(!a)return null;e=0;for(f=r.length;e<f;e++)if(r[e]&&r[e].target==a){r[e]=u(r[e]);break}a.scrollTop=0;a.scrollLeft=0;a.style.overflow=
"hidden";"static"==s.get(a,"position")&&s.set(a,"position","relative");"none"==s.get(a,"display")&&(s.set(a,"display","block"),v=!0);c=c||{};k=c.tag||m.tag;d={id:r.length,target:a,animate:void 0!=c.animate?c.animate:m.animate,useswipe:void 0!=c.useswipe?c.useswipe:m.useswipe,directionlock:void 0!=c.directionlock?c.directionlock:m.directionlock,slidermode:c.slidermode,wcp:["marginLeft","marginTop"]};(e=void 0!=c.usetransform?c.usetransform:m.usetransform)&&(l.support.transform&&(l.support.translate3d||
l.support.translate))&&(d.wcp=l.support.translate3d&&"translate3d"==e?["tx3d","ty3d"]:["tx","ty"]);d.handle={start:function(a){t.start(d,this,a)},end:function(a){t.end(d,a)},barmove:function(a){t.barmove(d,a)},wheel:function(a){t.wheel(d,a)},swipe:function(a){t.swipe(d,a)},swipeend:function(a){t.swipeend(d,a)},killautoscroll:function(a){g.killautoscroll(d)}};d.wrapper=p(d,k,n.content,"wrapper");l=a.childNodes;e=0;for(f=l.length;e<f;e++)d.wrapper.appendChild(l[e]),f--,e--;a.appendChild(d.wrapper);
l=d.wrapper.getElementsByTagName("*");e=0;for(f=l.length;e<f;e++)g.event.add(l[e],"focus",function(){var a=this;setTimeout(function(){d.target.scrollTop=0;d.scrollTo(a)},0)});l=["left","right","up","down"];for(e=0;2>e;e++)if(f=e?"y":"x",d[f]={},c[f]=c[f]||{},c.disable||c[f].disable)d[f].disable=!0,d[f].blockparentscroll=c[f].blockparentscroll||c.blockparentscroll||m.blockparentscroll;else{for(h in m)"animate"!=h&&("useswipe"!=h&&"tag"!=h&&"usetransform"!=h&&"directionlock"!=h)&&(d[f][h]=c[f][h]||
c[h]||m[h]);d[f].now=0;d[f].to=0;d[f].nowpage=0;d[f].totalpage=1;d[f].scrollsizelock&&(d[f].scrollsizefix?d[f].scrollsize=d[f].scrollsizefix:d[f].scrollsizefix=d[f].scrollsize);if(!d[f].hide){d[f].outsidetrack=w(d[f].outsidetrack);d[f].tracksizefix=!1;d[f].tracksize&&("number"==typeof d[f].tracksize?d[f].tracksizefix=!0:"string"==typeof d[f].tracksize&&(/^(\-|\+)[1-9]/.test(d[f].tracksize)?d[f].tracksize=parseInt(d[f].tracksize):d[f].tracksize=0));d[f].track=p(d,k,n[f][0],"track-"+f,f);d[f].trackhtml&&
(d[f].track.innerHTML=d[f].trackhtml);d[f].nointeract&&(d[f].track.style.pointerEvents="none");d[f].bar=p(d,k,n[f][1],"bar-"+f,f);d[f].barhtml&&(d[f].bar.innerHTML=d[f].barhtml);d[f].track.appendChild(d[f].bar);d[f].trackcontainer=d[f].outsidetrack||a;d[f].trackcontainer.appendChild(d[f].track);"static"==s.get(d[f].trackcontainer,"position")&&s.set(d[f].trackcontainer,"position","relative");d[f].arrowsize=[0,0];if(!d.slidermode)if(d[f].arrow=[p(d,k,n[f][2],"arrow-"+l[2*e],f),p(d,k,n[f][3],"arrow-"+
l[2*e+1],f)],d[f].track.appendChild(d[f].arrow[0]),d[f].track.appendChild(d[f].arrow[1]),d[f].arrow[0].offsetWidth){if("x"==f)for(h=0;2>h;h++)d[f].arrowsize[h]=d[f].arrow[h].offsetWidth+s.get(d[f].arrow[h],"marginLeft")+s.get(d[f].arrow[h],"marginRight");else for(h=0;2>h;h++)d[f].arrowsize[h]=d[f].arrow[h].offsetHeight+s.get(d[f].arrow[h],"marginTop")+s.get(d[f].arrow[h],"marginBottom");d[f].arrowsize[3]=d[f].arrowsize[0]+d[f].arrowsize[1]}else d[f].track.removeChild(d[f].arrow[0]),d[f].track.removeChild(d[f].arrow[1]),
d[f].arrow=null;"x"==f?(d[f].bar.style.width=0,d[f].bsizem=d[f].bar.offsetWidth):(d[f].bar.style.height=0,d[f].bsizem=d[f].bar.offsetHeight)}}if(d.x.disable&&d.y.disable)return u(d);d.x.hide||(d.y.hide||d.x.disable||d.y.disable||d.x.tracksizefix||d.y.tracksizefix||d.x.trackcontainer!=d.y.trackcontainer)||(d.neutralzone=p(d,k,n.neutralzone,"neutralzone"),d.x.trackcontainer.appendChild(d.neutralzone));d.reset=q.reset;d.remove=q.remove;d.scrollLeft=q.scrollLeft;d.scrollTop=q.scrollTop;d.scrollTo=q.scrollTo;
d.pageLeft=q.pageLeft;d.pageTop=q.pageTop;d.pageTo=q.pageTo;d.scrollWidth=q.scrollWidth;d.scrollHeight=q.scrollHeight;d.maxScrollLeft=q.maxScrollLeft;d.maxScrollTop=q.maxScrollTop;d.stop=q.stop;d.cancelSwipe=q.cancelSwipe;d.evs={};d.event={scrollstart:[],scroll:[],scrollend:[],pagechange:[],reset:[],add:function(a,b){return q.event.add(d,a,b)},remove:function(a,b){return q.event.remove(d,a,b)}};d.addEventListener=d.event.add;d.removeEventListener=d.event.remove;delete d.useswipe;r.push(d);return b?
d:g.reset(d,v)},scrollbar:{reset:function(){return g.reset(this)},remove:function(){return g.remove(this)},scrollLeft:function(a,c){return g.scrollLeft(this,a,c)},scrollTop:function(a,c){return g.scrollTop(this,a,c)},scrollTo:function(a,c,b){return g.scrollTo(this,a,c,b)},pageLeft:function(a,c){return g.pageLeft(this,a,c)},pageTop:function(a,c){return g.pageTop(this,a,c)},pageTo:function(a,c,b){return g.pageTo(this,a,c,b)},scrollWidth:function(){return g.scrollWidth(this)},scrollHeight:function(){return g.scrollHeight(this)},
maxScrollLeft:function(){return g.maxScrollLeft(this)},maxScrollTop:function(){return g.maxScrollTop(this)},stop:function(){return g.stop(this,!0)},cancelSwipe:function(){return g.cancelSwipe(this)},event:{add:function(a,c,b){c=c.toLowerCase();a.event[c]&&a.event[c].push(b);return a},remove:function(a,c,b){c=c.toLowerCase();if(a.event[c])for(var e=0,g=a.event[c].length;e<g;e++)a.event[c][e]==b&&(a.event[c].splice(e,1),g--,e--);return a}}},reset:function(a,c){var b,e,h=a.target,f=a.wrapper,d=g.browser,
l=g.style,k=g.classname,m=g.event,n=a.wcp;e=g.cssclass;var r=a.handle,t=a.x,p=a.y,q=["x y width clientWidth offsetWidth scrollWidth".split(" "),"y x height clientHeight offsetHeight scrollHeight".split(" ")];g.stop(a);7==d.ie&&(h.style.overflow="visible",f.style.zoom=0);for(i=0;2>i;i++)b=a[q[i][0]],b.disable||(l.set(f,n[i],0),b.hide||(b.track.style.display="none"),k.remove(f,e[q[i][0]][4]),b.clientsize=h[q[i][3]],b.contentsize=Math.max(h[q[i][5]],f[q[i][4]],f[q[i][5]]),7==d.ie&&f.getElementsByTagName("*").length&&
(b.contentsize=Math.max(b.contentsize,f.getElementsByTagName("*")[0][q[i][4]])),b.show=b.contentsize>b.clientsize,!b.show||(b.outsidetrack||b.hide)||k.add(f,e[q[i][0]][4]));a.neutralzone&&(a.neutralzone.style.display=t.show&&p.show?"block":"none");var s,k=!1;for(i=0;2>i;i++)(b=a[q[i][0]],e=a[q[i][1]],b.show)?(b.contentsize=Math.max(h[q[i][5]],f[q[i][4]],f[q[i][5]]),7==d.ie&&f.getElementsByTagName("*").length&&(b.contentsize=Math.max(b.contentsize,f.getElementsByTagName("*")[0][q[i][4]])),b.ablesize=
b.clientsize-b.contentsize,b.now&&(b.scrollsizefix&&b.nowpage&&(b.now=-b.scrollsizefix*b.nowpage),b.ablesize>b.now&&(b.now=b.ablesize),l.set(f,n[i],b.now)),b.to=b.now,b.scrollsizefix&&(t=Math.round(-b.now/b.scrollsizefix),s=Math.floor(Math.abs(b.ablesize/b.scrollsizefix))+1,t!=b.nowpage||s!=b.totalpage)&&(b.nowpage=t,b.totalpage=s,k=!0),b.hide||(b.tracksizefix?e=b.tracksize:(!b.outsidetrack||e.outsidetrack&&b.outsidetrack==e.outsidetrack?e.show&&b.trackcontainer==e.trackcontainer?(e.track.style.display=
"block",e=b.trackcontainer[q[i][3]]-e.track[q[i][4]]):e=b.trackcontainer[q[i][3]]:e=b.trackcontainer[q[i][3]],e+=b.tracksize),l.set(b.track,q[i][2],Math.max(e,0)),e=b.arrowsize[0]?e-b.arrowsize[3]:e,b.bnowsize="auto"==b.barsize?Math.max(Math.round(e*(b.clientsize/b.contentsize)),b.barminsize):b.barsize,b.bnowsize-=b.bsizem,l.set(b.bar,q[i][2],b.bnowsize),b.bminpos=b.arrowsize[0],b.bmaxpos=b.bminpos+e-b.bnowsize-b.bsizem,g.movebar(a,q[i][0],b.now),b.track.style.display="block")):(b.now=0,b.ablesize=
0);7==d.ie&&(h.style.overflow="hidden",f.style.zoom=1);d.mobile||a.slidermode||(p.show?(m.add(f,"mousewheel",r.wheel),p.hide||m.add(p.track,"mousewheel",r.wheel)):p.disable||(m.remove(f,"mousewheel",r.wheel),p.hide||m.remove(p.track,"mousewheel",r.wheel)));c&&l.set(a.target,"display","none");k&&g.scrollevent.load(a,"pagechange");g.scrollevent.load(a,"reset");return a},scroll:function(a,c,b,e,h,f){var d,l=a.wrapper,k="x"==c||"left"==c||"right"==c?"x":"y",m=a.wcp["x"==k?0:1],n=a[k];!e&&0<b&&(b=Math.round(n.ablesize*
((b-n.bminpos)/(n.bmaxpos-n.bminpos))));c=Math.round(void 0!=b?b:"up"==c||"left"==c?n.to+n.scrollsize:n.to-n.scrollsize);n.scrollsizefix&&(c=Math.round(c/n.scrollsizefix)*n.scrollsizefix);c=0<c?0:c<n.ablesize?n.ablesize:c;n.scrollsizefix&&(d=g.setpage(a,k,c),n.scrollsizelock&&(c=-n.nowpage*n.scrollsizefix));if(f)return[c,d];if(a.slidermode||n.to!=c)d&&g.scrollevent.load(a,"pagechange"),n.to=c,g.ani.stop(l),a.animate&&!h?(h={},h[m]=c,g.handle.animate(a,h,void 0==b||e)):(n.now=c,g.style.set(l,m,c),
(void 0==b||e||0===e)&&g.movebar(a,k,c,!1,h),g.scrollevent.load(a,"ing"))},scrollevent:{load:function(a,c,b){var e=a.event,h=a.evs.scrollstartfired,f=g.scrollevent.fire;"start"==c&&!h&&a.animate?(e.scrollstart.length&&f(a,"scrollstart"),a.evs.scrollstartfired=!0):"ing"==c&&e.scroll.length?f(a,"scroll"):"end"==c?(b&&g.scrollevent.load(a,"ing"),h&&(e.scrollend.length&&f(a,"scrollend"),a.evs.scrollstartfired=!1)):("pagechange"==c||"reset"==c)&&e[c].length&&f(a,c)},fire:function(a,c){for(var b=g.scrollevent.bullet(a,
c),e=a.event[c],h=0,f=e.length;h<f;h++)e[h].call(a,b)},bullet:function(a,c){var b=a.x,e=a.y;return{type:c,scrollLeft:-b.now,scrollTop:-e.now,scrollWidth:Math.max(b.contentsize,b.clientsize)||0,scrollHeight:Math.max(e.contentsize,e.clientsize)||0,pageLeft:b.nowpage||0,pageTop:e.nowpage||0,totalPageLeft:b.totalpage||0,totalPageTop:e.totalpage||0,barLeft:b.bar&&b.bar.offsetLeft||0,barTop:e.bar&&e.bar.offsetTop||0,barWidth:b.bar&&b.bar.offsetWidth||0,barHeight:e.bar&&e.bar.offsetHeight||0}}},autoscroll:function(a,
c,b,e){if(a.slidermode)e||(b=Math.max(b-a[c].bnowsize/2,0)),g.scroll(a,c,b,0);else{var h=a.x,f=a.y;g.killautoscroll(a);g.event.add(document,"mouseup",a.handle.killautoscroll);void 0!=b?c="x"==c?h.bar.offsetLeft+h.bar.offsetWidth>b?"left":"right":f.bar.offsetTop+f.bar.offsetHeight>b?"up":"down":(c=c.match(/arrow-([a-z]+)/)[1],b="up"==c?f.bminpos:"down"==c?f.bmaxpos+f.bar.offsetHeight:"left"==c?h.bminpos:h.bmaxpos+h.bar.offsetWidth);var d=!0,l=function(){"left"==c&&h.bar.offsetLeft<=b||"right"==c&&
h.bar.offsetLeft+h.bar.offsetWidth>=b||"up"==c&&f.bar.offsetTop<=b||"down"==c&&f.bar.offsetTop+f.bar.offsetHeight>=b?g.killautoscroll(a):(g.scroll(a,c),a.evs.astimer=setTimeout(l,d?500:30),d=!1)};l()}},killautoscroll:function(a){clearTimeout(a.evs.astimer);g.event.remove(document,"mouseup",a.handle.killautoscroll)},scrollLeft:function(a,c,b){var e;if(e=g.getoffset(a,c))a.scrollLeft(e[0]);else{if(isNaN(parseInt(c)))return-a.x.now;g.scroll(a,"x",-c,!0,b)}},scrollTop:function(a,c,b){var e;if(e=g.getoffset(a,
c))a.scrollTop(e[1]);else{if(isNaN(parseInt(c)))return-a.y.now;g.scroll(a,"y",-c,!0,b)}},getoffset:function(a,c){var b,e,h,f,d=g.findelement(c);if(d){e=document.body;h=f=0;b=g.style.get(a.wrapper,"position");for(a.wrapper.style.position="relative";d!=a.wrapper&&d!=e;)h+=d.offsetLeft,f+=d.offsetTop,d=d.offsetParent;a.wrapper.style.position=b;return d==e?!1:[h,f]}return!1},scrollTo:function(a,c,b,e){var h,f,d,l,k,m,n=arguments;property={};wrapper=a.wrapper;wcp=a.wcp;for(h=1;3>h;h++)l=(d=g.getoffset(a,
n[h])||d)||!n[h]&&d?d[h-1]:n[h],isNaN(parseInt(l))||(f=2>h?"x":"y",l=g.scroll(a,f,-l,!1,!1,!0),a[f].to!=l[0]&&(k=!0),l[1]&&(m=!0),property[wcp[h-1]]=a[f].to=l[0]);if(k)if(m&&g.scrollevent.load(a,"pagechange"),a.animate&&!e)g.handle.animate(a,property,!0);else{for(h=0;2>h;h++)isNaN(property[wcp[h]])||(f=h?"y":"x",a[f].now=a[f].to=property[wcp[h]],g.style.set(wrapper,wcp[h],property[wcp[h]]),g.movebar(a,f,property[wcp[h]]));g.scrollevent.load(a,"ing")}},pageLeft:function(a,c,b){if(isNaN(c))return a.x.nowpage;
g.scrollLeft(a,c*a.x.scrollsizefix,b)},pageTop:function(a,c,b){if(isNaN(c))return a.y.nowpage;g.scrollTop(a,c*a.y.scrollsizefix,b)},pageTo:function(a,c,b,e){isNaN(c)||isNaN(b)||g.scrollTo(a,c*a.x.scrollsizefix,b*a.y.scrollsizefix,e)},scrollWidth:function(a){return-a.x.contentsize},scrollHeight:function(a){return-a.y.contentsize},maxScrollLeft:function(a){return-a.x.ablesize},maxScrollTop:function(a){return-a.y.ablesize},stop:function(a,c){g.ani.stop(a.wrapper);var b,e,h;for(b=0;2>b;b++)e=b?"y":"x",
h=a[e],h.disable||(h.now=h.to=0<h.now?0:h.ablesize>h.now?h.ablesize:Math.round(h.now),g.style.set(a.wrapper,a.wcp[b],h.now),g.movebar(a,e,h.now,!0));g.eventkiller.killed&&g.eventkiller.leave();if(c)return g.scrollevent.load(a,"end",!0),g.event.remove(document,"mousemove",a.handle.swipe,a.id),g.event.remove(document,"mouseup",a.handle.swipeend,a.id),a},cancelSwipe:function(a){g.event.remove(document,"mousemove",a.handle.swipe,a.id);return a},movebar:function(a,c,b,e,h){var f=a[c];if(f.show&&!f.hide){b=
f.bminpos+(f.bmaxpos-f.bminpos)*(b/f.ablesize);var d="x"==c?"left":"top";e&&(e="x"==c?["offsetHeight","width"]:["offsetWidth","height"],c=f.bnowsize,f.bminpos>b?(c=Math.round(f.bnowsize+4*(b-f.bminpos)),f.bar[e[0]]-f.bsizem>c&&(c=f.bar[e[0]]-f.bsizem),b=f.bminpos):b>f.bmaxpos&&(c=Math.round(f.bnowsize+4*(f.bmaxpos-b)),f.bar[e[0]]-f.bsizem>c&&(c=f.bar[e[0]]-f.bsizem),b=f.bmaxpos+f.bnowsize-c),g.style.set(f.bar,e[1],c));a.slidermode&&!h?(a={},a[d]=b,g.ani.set(f.bar,a,{time:0.5,rounding:!0})):g.style.set(f.bar,
d,b)}},setpage:function(a,c,b){a=a[c];b=Math.round(-b/a.scrollsizefix);b=0>b?0:b>a.totalpage-1?a.totalpage-1:b;return b!=a.nowpage?(a.nowpage=b,!0):!1},handle:{start:function(a,c,b){var e,h=a.evs,f=a.handle,d=g.browser,l=g.event.add;a.slidermode?g.ani.stop(a[a.y.disable?"x":"y"].bar):g.stop(a);h.swdrt=0;e=c.dataset.fsflag;h.target=c;if("wrapper"==e){c=b.target||b.srcElement;e=c.nodeName.toLowerCase();if("input"==e||"select"==e||"textarea"==e){if("input"==e&&"range"==c.type||"select"==e&&!d.mobile&&
d.webkit)return!0;h.fcusel=c}else!d.mobile&&b.preventDefault&&b.preventDefault();h.sweventdead=!1;h.offsetpos=[a.x.now,a.y.now];h.clientpos=h.swbasepos=g.handle.getpoint(b);h.swstime=(new Date).getTime();l(document,"mousemove",f.swipe,a.id);l(document,"mouseup",f.swipeend,a.id);return!0}/track/.test(e)?(c=b.target||b.srcElement,e=e.match(/track-([a-z]+)/)[1],g.autoscroll(a,e,"x"==e?(b.offsetX||b.layerX)+c.offsetLeft:(b.offsetY||b.layerY)+c.offsetTop)):/arrow/.test(e)?g.autoscroll(a,e):("bar-x"==e?
(h.offsetpos=c.offsetLeft,h.clientpos=g.handle.getpoint(b)[0]):(h.offsetpos=c.offsetTop,h.clientpos=g.handle.getpoint(b)[1]),g.classname.add(c,"active"),l(document,"mousemove",f.barmove),l(document,"mouseup",f.end));return g.handle.killevent(b,!0)},end:function(a,c){g.classname.remove(a.evs.target,"active");g.event.remove(document,"mousemove",a.handle.barmove);g.event.remove(document,"mouseup",a.handle.end)},barmove:function(a,c){var b,e=a.evs,h=e.target.dataset.fsflag.match(/bar-(x|y)/)[1],f=a[h],
d="x"==h?"left":"top";b=g.handle.getpoint(c)["x"==h?0:1];e.clientpos!=b&&(b=e.offsetpos-(e.clientpos-b),f.bminpos>b?b=f.bminpos:b>f.bmaxpos&&(b=f.bmaxpos),g.style.set(e.target,d,b),g.scroll(a,h,b));return g.handle.killevent(c)},wheel:function(a,c){var b=c.wheelDelta||c.detail,e=a.y;g.browser.firefox&&(b*=-1);if(!e.blockparentscroll&&(0<b&&0==e.now||0>b&&e.now==e.ablesize))return!0;g.scroll(a,0<b?"up":"down");return g.handle.killevent(c,!0)},swipe:function(a,c){if(a.evs.sweventdead)return!0;var b=
a.evs,e=g.handle,h=e.getpoint(c),f=(new Date).getTime(),d,l,k="marginLeft"==a.wcp[0],m=[],n=[],r=["x","y"];l=a.x;var t=a.y;for(d=0;2>d;d++)m[d]=b.clientpos[d]-h[d],n[d]=b.offsetpos[d]-m[d];if(!b.swdrt&&(Math.abs(m[0])||Math.abs(m[1]))){d=Math.abs(180*Math.atan2(m[0],m[1])/Math.PI);b.swdrt=!l.blockparentscroll||t.disable||l.show&&!l.disable?!t.blockparentscroll||l.disable||t.show&&!t.disable?a.directionlock?45>d||135<d?"y":100>d&&80<d?"x":"f":"f":"x":"y";for(d=0;2>d;d++)if(l=a[r[d]],!l.blockparentscroll&&
b.swdrt==r[d]&&(0>m[d]&&0==l.now||0<m[d]&&l.now==l.ablesize))return d=d?0:1,l=a[r[d]],l.scrollsizefix&&(b={},b[a.wcp[d]]=Math.round(l.now/l.scrollsizefix)*l.scrollsizefix,g.setpage(a,r[d],b[a.wcp[d]]),b[a.wcp[d]]=g.ani.getvalues("",l.now,b[a.wcp[d]],g.ani.fps/2,"easeOutExpo",k),e.animate(a,b,!0,!0,0.5)),e.removeswipehandle(a),!0;b.fcusel&&(b.fcusel.blur(),b.fcusel=null);e.removeswipehandle(a,!0);g.eventkiller.killed||g.browser.mobile||g.eventkiller.call(a.target)}f-300>b.swstime&&(b.swstime=f,b.swbasepos=
h);g.scrollevent.load(a,"start");for(d=0;2>d;d++)l=a[r[d]],!l.show&&!l.blockparentscroll||"f"!=b.swdrt&&b.swdrt!=r[d]||(0<n[d]?n[d]/=2:l.ablesize>n[d]&&(n[d]-=(n[d]-l.ablesize)/2),l.now=l.to=n[d],g.style.set(b.target,a.wcp[d],n[d]),g.movebar(a,r[d],n[d],!0));g.scrollevent.load(a,"ing");return e.killevent(c)},swipeend:function(a,c){var b=a.evs,e=g.handle,h=e.getpoint(c),f={},d,l=(new Date).getTime()-b.swstime,k,m,n,r,t=[],p=[],q=null,s=[],w=!1,u=g.ani.fps,v="marginLeft"==a.wcp[0];for(k=0;2>k;k++){q=
null;m=k?"y":"x";d=a[m];s[k]=b.swbasepos[k]-h[k];if((d.show||d.blockparentscroll)&&(!s[k]&&d.scrollsizefix||"f"==b.swdrt||b.swdrt==m)&&5<Math.abs(s[k]))if(d.scrollsizelock)0<d.now||d.ablesize>d.now?Math.abs(s[k])>d.scrollsizefix&&(t[k]=0<s[k]?d.nowpage+1:d.nowpage-1):300>l&&(t[k]=0<s[k]?d.nowpage+1:d.nowpage-1),void 0==t[k]&&(currentpage=Math.round(-d.now/d.scrollsizefix),t[k]=currentpage>d.nowpage?d.nowpage+1:d.nowpage>currentpage?d.nowpage-1:currentpage),t[k]=0>t[k]?0:t[k]>d.totalpage-1?d.totalpage-
1:t[k],p[k]=g.ani.getvalues("",d.now,-t[k]*d.scrollsizefix,u,"easeOutExpo",v);else if(300>l&&s[k]){r=Math.round(d.now-s[k]*((300-l)/25));d.scrollsizefix&&(r=Math.round(r/d.scrollsizefix)*d.scrollsizefix);if(0<s[k]&&r>-d.now||0>s[k]&&d.ablesize+d.ablesize-d.now>r)r=0<s[k]?0:d.ablesize,p[k]=g.ani.getvalues(a.wcp[k],d.now,r,u/2,"easeOutCubic",v);else{if(0>s[k]&&0<d.now||0<s[k]&&d.ablesize>d.now)q=d.now-s[k]/4,p[k]=g.ani.getvalues("",d.now,q,u/10,"easeOutCubic",v),m=p[k].length;else for(p[k]=g.ani.getvalues("",
d.now,r,2*u,"easeOutCubic",v),m=0,n=p[k].length;m<n;m++)if(0>s[k]){if(0<p[k][m]){null==q&&(q=7*Math.abs((p[k][m-1]||0)-p[k][m]));if(p[k][m]>q){p[k][m]/=2;m+=1;p[k].length=m;break}p[k][m]/=2}}else if(d.ablesize>p[k][m]){null==q&&(q=d.ablesize-7*((p[k][m-1]||d.ablesize)-p[k][m]));if(q>p[k][m]){p[k][m]-=(p[k][m]-d.ablesize)/2;m+=1;p[k].length=m;break}p[k][m]-=(p[k][m]-d.ablesize)/2}if(0>s[k]&&0<p[k][m-1]||0<s[k]&&d.ablesize>p[k][m-1])r=0>s[k]?0:d.ablesize,p[k]=p[k].concat(g.ani.getvalues("",p[k][m-1],
r,u/2,"easeOutCubic",v))}d.scrollsizefix&&(t[k]=Math.round(-r/d.scrollsizefix))}p[k]||(r=0<d.now?0:d.ablesize>d.now?d.ablesize:Math.round(d.now),d.scrollsizefix&&(r=Math.max(d.ablesize,Math.round(r/d.scrollsizefix)*d.scrollsizefix),t[k]=Math.round(-r/d.scrollsizefix),t[k]=0>t[k]?0:t[k]>d.totalpage-1?d.totalpage-1:t[k]),p[k]=g.ani.getvalues("",d.now,r,u/2,"easeOutCubic",v));t[k]!=d.nowpage&&(d.nowpage=t[k],w=!0);f[a.wcp[k]]=p[k]}w&&g.scrollevent.load(a,"pagechange");void 0!=f[a.wcp[0]]||void 0!=f[a.wcp[1]]?
e.animate(a,f,!0,!0,2):g.scrollevent.load(a,"end");e.removeswipehandle(a);if(g.eventkiller.killed)return g.eventkiller.leave(),e.killevent(c)},animate:function(a,c,b,e,h){g.ani.set(a.wrapper,c,{time:h,rounding:"marginLeft"==a.wcp[0],onstart:function(){g.scrollevent.load(a,"start")},onupdate:function(c){g.handle.onanimate(a,c,b,e)},onend:function(c){g.handle.onanimate(a,c,b,e)}})},onanimate:function(a,c,b,e){var h,f,d=a.wcp;for(h=0;2>h;h++)f=h?"y":"x",void 0!=c[d[h]]&&(a[f].now=c[d[h]],e&&(a[f].to=
a[f].now),b&&g.movebar(a,f,c[d[h]],e));g.scrollevent.load(a,"update"==c.type?"ing":"end",!0)},removeswipehandle:function(a,c){var b=g.event.remove;if(c){var e,h=["x","y"],f=g.items.length;for(c=a.target.parentNode;"body"!=c.nodeName.toLowerCase();){for(e=0;e<f;e++)if((b=g.items[e])&&b.target==c){b.evs.swdrt="q";b.stop();b.evs.sweventdead=!0;if(9>g.browser.ie)for(e=0;2>e;e++)b[h[e]].now=b[h[e]].to=b.evs.offsetpos[e],g.style.set(b.wrapper,b.wcp[e],b[h[e]].now),g.movebar(b,h[e],b[h[e]].now,!0);break}c=
c.parentNode}}else b(document,"mousemove",a.handle.swipe,a.id),b(document,"mouseup",a.handle.swipeend,a.id)},getpoint:function(a){return g.browser.mobile?[a.touches[0]?a.touches[0].pageX:a.changedTouches[0].pageX,a.touches[0]?a.touches[0].pageY:a.changedTouches[0].pageY]:[a.clientX,a.clientY]},killevent:function(a,c){a.stopPropagation&&(a.stopPropagation(),c&&a.preventDefault&&a.preventDefault());a.cancelBubble=!0;return a.returnValue=!1}},remove:function(a){var c=a.target,b=a.wrapper,e=a.x.track,
h=a.y.track;if(b){for(var f=b.childNodes,d=0,l=f.length;d<l;d++)c.appendChild(f[d]),l--,d--;c.removeChild(b)}e&&(e.parentNode.style.position="",e.parentNode.removeChild(e));h&&(h.parentNode.style.position="",h.parentNode.removeChild(h));c.style.overflow="";d=0;c=g.items;for(l=c.length;d<l;d++)if(c[d]==a){c[d]=null;break}return null},event:{typeinmobile:{mouseover:"touchstart",mousedown:"touchstart",mousemove:"touchmove",mouseout:"touchend",mouseup:"touchend"},type:function(a){var c=g.browser,b=g.event.typeinmobile;
return c.mobile&&b[a]?b[a]:c.firefox&&"mousewheel"==a?"DOMMouseScroll":a},add:function(a,c,b,e){c=g.event.type(c);a.addEventListener?a.addEventListener(c,b,!1):(a[c+e+b]=function(){b.call(a,window.event)},a.attachEvent("on"+c,a[c+e+b]))},remove:function(a,c,b,e){c=g.event.type(c);a.removeEventListener?a.removeEventListener(c,b,!1):a[c+e+b]&&(a.detachEvent("on"+c,a[c+e+b]),a[c+e+b]=null)}},classname:{add:function(a,c){this.set("add",a,c)},remove:function(a,c){this.set("remove",a,c)},set:function(a,
c,b){var e=(" "+c.className).replace(RegExp(" "+b,"g"),"");c.className=("add"==a?e+" "+b:e).replace(/^ +/,"")}},style:{exp:[[/translate3d\(([e0-9\-\.]+)(?:px)?, ([e0-9\-\.]+)(?:px)?/,/(translate3d\()[e0-9\-\.]+(?:px)?/,/(translate3d\([e0-9\-\.]+(?:px)?, )[e0-9\-\.]+(?:px)?/],[/translate\(([e0-9\-\.]+)(?:px)?, ([e0-9\-\.]+)(?:px)?/,/(translate\()[e0-9\-\.]+(?:px)?/,/(translate\([e0-9\-\.]+(?:px)?, )[e0-9\-\.]+(?:px)?/]],get:function(a,c){var b,e,h=g.browser.support;/^t(x|y)(3d)?/.test(c)?(e=c,c=h.transform):
"opacity"!=c||h.opacity||(c="filter");b=a.style[c]?a.style[c]:a.currentStyle?a.currentStyle[c]:document.defaultView.getComputedStyle(a,null)[c];return c==h.transform?/3d/.test(e)?(b=b.match(g.style.exp[0][0]))?parseInt("tx3d"==e?b[1]:b[2]):0:(b=b.match(g.style.exp[1][0]))?parseInt("tx"==e?b[1]:b[2]):0:"opacity"==c?parseFloat(b):"filter"==c?(b=parseFloat(b.match(/alpha *\( *opacity *[=:] *([0-9\.]+) *\)/i)[1]))||0===b?b/100:1:"auto"==b?0:/(pt|px)$/.test(b)?parseInt(b):b},set:function(a,c,b){var e=
g.browser.support;void 0!=b&&(/^t(x|y)(3d)?/.test(c)?/3d/.test(c)?a.style[e.transform]=a.style[e.transform].replace(g.style.exp[0]["tx3d"==c?1:2],"$1"+b+"px"):a.style[e.transform]=a.style[e.transform].replace(g.style.exp[1]["tx"==c?1:2],"$1"+b+"px"):"opacity"==c?e.opacity?a.style.opacity=b:a.style.filter="alpha(opacity="+100*b+")":a.style[c]=isNaN(b)?b:b+"px")}},createtag:function(a,c,b,e,h){c=document.createElement(c);var f=g.browser.support;c.dataset||(c.dataset={},9>g.browser.ie&&(c.style.filter=
"inherit"));c.dataset.fsflag=e;c.className=b;"wrapper"==e?/^t(x|y)(3d)?/.test(a.wcp[0])&&(c.style[f.transform]+=" "+(/3d/.test(a.wcp[0])?f.translate3d:f.translate)):c.style.position="absolute";("wrapper"==e&&a.useswipe||"neutralzone"!=e&&h&&!a[h].nointeract)&&g.event.add(c,"mousedown",a.handle.start);return c},findelement:function(a){"string"==typeof a&&(a=document.getElementById(a));return a&&a.nodeType&&1==a.nodeType?a:null},ani:{fps:72,time:1,easing:"easeOutQuint",target:[],timer:[],set:function(a,
c,b){b=b||{};var e,h=0,f=g.ani.no(a),d=b.time||g.ani.time,l=Math.round(d*g.ani.fps),k={};clearTimeout(g.ani.timer[f]);for(e in c)k[e]=c[e].length?c[e]:g.ani.getvalues(e,g.style.get(a,e),c[e],l,b.easing||g.ani.easing,b.rounding),h=Math.max(k[e].length,h);if(2>h){for(e in c)c[e]=c[e][0];c.type="end";c.percent=1;b.onend&&b.onend.call(a,c)}else{var m,n,r=1E3*d/l,t=function(){var d=Math.round(l*(((new Date).getTime()-m)/(n-m))),e,s={};if(h-1>d){for(e in c)s[e]=k[e][d],g.style.set(a,e,s[e]);s.type="update";
b.onupdate&&b.onupdate.call(a,s);g.ani.timer[f]=setTimeout(t,r)}else{for(e in c)s[e]=k[e][k[e].length-1],g.style.set(a,e,s[e]);s.type="end";b.onend&&b.onend.call(a,s)}};g.ani.timer[f]=setTimeout(function(){m=(new Date).getTime();n=m+1E3*d;b.onstart&&b.onstart.call(a,{type:"start"});t()},1E3*(b.delay||0))}},stop:function(a){clearTimeout(g.ani.timer[g.ani.no(a)])},no:function(a){for(var c=0,b=g.ani.target.length;c<b;c++)if(a==g.ani.target[c])return c;g.ani.target.push(a);return g.ani.target.length-
1},getvalues:function(a,c,b,e,h,f){for(var d,l=[],k=b-c,m=g.ani.equations,n=1;n<=e&&(d=m[h](n,c,k,e),l.push("opacity"==a?parseInt(1E3*d)/1E3:f?Math.round(d):d),d!=b);n++);return l},equations:{linear:function(a,c,b,e){return b*a/e+c},easeOutCubic:function(a,c,b,e){return b*((a=a/e-1)*a*a+1)+c},easeOutQuint:function(a,c,b,e){return b*((a=a/e-1)*a*a*a*a+1)+c},easeOutExpo:function(a,c,b,e){return a==e?c+b:1.001*b*(-Math.pow(2,-10*a/e)+1)+c}}},eventkiller:{killer:null,killed:!1,call:function(a){a.appendChild(g.eventkiller.killer);
g.eventkiller.killed=!0},leave:function(){g.eventkiller.killer.parentNode.removeChild(g.eventkiller.killer);g.eventkiller.killed=!1}}};g.browser=function(){var a={support:{fixed:!0,opacity:!0,transform:!1}},c=navigator.userAgent,b=c.match(/msie ([0-9])+/i);b&&(b=parseInt(b[1]),7>b&&(a.support.fixed=!1),9>b&&(a.support.opacity=!1),a.ie=b);a.firefox=/firefox/i.test(c);a.webkit=/applewebkit/i.test(c);a.opera=/opera/i.test(c);a.ios=/ip(ad|hone|od)/i.test(c);a.android=/android/i.test(c);a.mobile=
document.ontouchstart!==undefined;c=document.createElement("div");b="position:absolute;left:0;top:0;width:100%;height:100%;background:#f60;z-index:10000;opacity:0;";a.support.opacity||(b+="filter:alpha(opacity=0)");c.style.cssText=b;var b=["t","WebkitT","MozT","OT","msT"],e="ransform";if(c.style.hasOwnProperty)for(var h=0;5>h;h++)if(void 0!=c.style[b[h]+"ransition"]&&(a.support.transition=b[h]+"ransition"),void 0!=c.style[b[h]+e]){e=b[h]+e;a.support.transform=e;c.style[e]=
"translate3d(0px, 0px, 0px)";a.support.translate3d=c.style[e];c.style[e]="translate(0px, 0px)";a.support.translate=c.style[e];c.style[e]="";break}g.eventkiller.killer=c;return a}();g.preset=function(a,c,b,e){a=g.findelement(a);if(!a)return null;b=b||{};b.x=b.x||{};b.y=b.y||{};return g.presetlist[c](a,b,e)};g.presetlist={"ios-mode":function(a,c,b){g.classname.add(a,g.cssclass.iosmode);c.animate=!0;c.tracksize=c.tracksize||"-2";c.nointeract=!0;c.barminsize=35;var e,h,f=g.set(a,c);f.display=function(a,
b){a=a||{type:"blank"};if("scrollstart"==a.type||"blank"==a.type){for(e=0;2>e;e++)h=f[e?"y":"x"],h.disable||h.hide||(g.ani.stop(h.bar),g.style.set(h.bar,"opacity",0.5));"blank"==a.type&&f.display({},0.5)}else for(e=0;2>e;e++)h=f[e?"y":"x"],h.disable||h.hide||g.ani.set(h.bar,{opacity:0},{easing:"linear",time:0.25,delay:b})};f.addEventListener("scrollstart",f.display).addEventListener("scrollend",f.display);if(b)for(e=0;2>e;e++)h=f[e?"y":"x"],h.disable||h.hide||g.style.set(h.bar,"opacity",0);else f.display({type:"scrollstart"}),
f.display({},1);return f},"show-only-over":function(a,c){var b=g.set(a,c),e,h,f=!1,d=!1,l=function(a,c){d=a&&("mouseover"==a.type||"touchstart"==a.type);if(!f){for(e=0;2>e;e++)h=b[e?"y":"x"],!h.disable&&h.show&&g.ani.set(h.track,{opacity:d?1:0},{easing:"linear",time:0.2,delay:c});b.neutralzone&&b.neutralzone.offsetWidth&&g.ani.set(b.neutralzone,{opacity:d?1:0},{easing:"linear",time:0.2,delay:c})}},k=function(){f=!0;g.event.add(document,"mouseup",m,b.id)},m=function(){f=!1;d||l("",0);g.event.remove(document,
"mouseup",m,b.id)};g.event.add(b.target,"mouseover",l);g.event.add(b.target,"mouseout",l);for(e=0;2>e;e++)h=b[e?"y":"x"],h.disable||h.hide||(g.style.set(h.track,"opacity",1),g.event.add(h.bar,"mousedown",k));b.neutralzone&&b.neutralzone.offsetWidth&&g.style.set(b.neutralzone,"opacity",1);l("",1);return b},"slider-x":function(a,c){return g.presetter.slider(a,c,"x")},"slider-y":function(a,c){return g.presetter.slider(a,c,"y")},"switch-x":function(a,c){return g.presetter["switch"](a,c,"x")},"switch-y":function(a,
c){return g.presetter["switch"](a,c,"y")}};g.presetter={slider:function(a,c,b){if(void 0==c.barsize||void 0==c.min||void 0==c.max||c.min==c.max||c.min>c.max)return null;var e,h;"x"==b?(c.y.disable=!0,e="clientWidth",h="Left"):(c.x.disable=!0,e="clientHeight",h="Top");var f=c.max-c.min,d=a[e],l=d+f;e=c.step||1;var k=Math.round((void 0!=c.value?c.value:c.min)/e)*e;c.min>k&&(k=c.min);c.animate=!1;c.slidermode=!0;c.scrollsizefix=e;var m=g.set(a,c,!0);"x"==b?(g.style.set(m.wrapper,"width",l),g.style.set(m.wrapper,
"height",1)):(g.style.set(m.wrapper,"width",1),g.style.set(m.wrapper,"height",l));g.style.set(m.wrapper,"opacity",0);m.reset();m["scroll"+h]((l-d)*((k-c.min)/f),!0);m.addEventListener("scroll",function(a){a=c.min+f*a["scroll"+h]/(l-d);k!=a&&(c.onchange&&c.onchange(a),k=a)});var n=!1,r=function(){n&&(g.autoscroll(m,b,m[b].bar["offset"+h],!0),n=!1);g.event.remove(document,"mouseup",r,m.id)};g.event.add(m[b].bar,"mousedown",function(){n=!0;g.event.add(document,"mouseup",r,m.id)});return m},"switch":function(a,
c,b){if(void 0==c.barsize)return null;c.min=0;c.max=a["x"==b?"clientWidth":"clientHeight"];c.step=c.max;c.value=c.value?c.step:0;var e,h=c.onchange;c.onchange=function(a){c.value=a;h&&h(c.value?!0:!1);e=!0};var f=g.presetter.slider(a,c,b),d=function(){e||setTimeout(function(){f["x"==b?"scrollLeft":"scrollTop"](c.value?0:c.step)},0);g.event.remove(document,"mousemove",k,f.id);g.event.remove(document,"mouseup",d,f.id)},l;a=function(a){e=!1;l=g.handle.getpoint(a);g.event.add(document,"mousemove",k,f.id);
g.event.add(document,"mouseup",d,f.id)};var k=function(a){a=g.handle.getpoint(a);if(l[0]!=a[0]||l[1]!=a[1])e=!0};g.event.add(f[b].bar,"mousedown",a);g.event.add(f[b].track,"mousedown",a);return f}};return g}();